Correct path to jbrowse config files on volume
Fixes issues described by Daniel in this PR:
"Overall, it looks nice. I noticed that Clicking on Browse the genome give me this JBrowse error:
Error: HTTP 404 fetching /data/parnassius_mnemosyne/config.json
but I do not know if that is related to the new image. ./scripts/dockermake.sh install copies files to hugo/static as expected. Was there one more step to move data from hugo/static to hugo/data that I need to run?"